# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# https://dev.azure.com/liangyuanpeng/lanactions
trigger:
  branches:
    include:
      - main
      - pulsar

pr:
  - "*"

schedules:
  - cron: "0 0,1,4,6,8,22 * * *" # 每天半夜构建
    displayName: Daily midnight build
    always: true #默认是上次成功运行后或有新的提交
    branches:
      include:
      - main
      - pulsar

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    docker images
    go version
    free -mh
    docker rmi `docker images -aq`
    df -h
  displayName: "check env"

- script: |
    export GOFLAGS="-p=2"
    git clone https://github.com/kubernetes/kubernetes
    export KUBEROOT=$PWD/kubernetes
    git clone https://github.com/kubernetes-sigs/kind
    cd kind
    hack/release/build/push-node.sh 
    docker images
  displayName: "build kind node"

